### ISSUE TITLE
Fix Remaining ships color schema in Fullscreen mode

### ISSUE THREAD

**Issue by np25071984** [np25071984/battleships#1]
it is hard to read the "Opponent's remaining ships" section when it is Fullscreen mode. I don't know why the background color becomes black but we have to consider it.

<img width="711" alt="image" src="https://github.com/GHopperMSK/battleships/assets/19670887/f7759d4b-92ca-4ef9-a4c0-53b25a3181b6">

**Comment by CzhCN0** [comment]
@np25071984 Hi mate. The change in background color to black is due to the default styles added by Chrome when handling fullscreen mode. The following CSS takes effect when a non-root element is in fullscreen mode. You only need to add a background color to the "game-boards" element, or alternatively, use a vibrant seascape background.

:not(:root):fullscreen::backdrop {
    position: fixed;
    inset: 0px;
    background: black;
}

**Comment by np25071984** [comment]
@CzhCN0 thank you for the response! 

> the default styles added by Chrome when handling fullscreen mode

I think those `default styles` make sense so that it is better to update the text color and follow default fullscreen logic
